
//! Autogenerated weights for pallet_insurance_vault
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2025-06-13, STEPS: `20`, REPEAT: `10`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `lujundeMacBook-Pro-2.local`, CPU: `<UNKNOWN>`
//! EXECUTION: None, WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/release/substrate
// benchmark
// pallet
// --chain
// dev
// --pallet
// pallet_insurance_vault
// --extrinsic
// *
// --steps
// 20
// --repeat
// 10
// --wasm-execution
// compiled
// --output
// frame/insurance-vault/src/weights.rs
// --template
// ./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for pallet_insurance_vault.
pub trait WeightInfo {
	fn stake() -> Weight;
	fn add_reward() -> Weight;
	fn claim() -> Weight;
	fn unstake() -> Weight;
	fn exit() -> Weight;
	fn set_min_stake_duration() -> Weight;
	fn compensate() -> Weight;
}

/// Weights for pallet_insurance_vault using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: InsuranceVault UserStake (r:1 w:1)
	/// Proof: InsuranceVault UserStake (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	/// Storage: Assets Asset (r:1 w:1)
	/// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
	/// Storage: Assets Account (r:2 w:2)
	/// Proof: Assets Account (max_values: None, max_size: Some(134), added: 2609, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: InsuranceVault TotalStake (r:1 w:1)
	/// Proof: InsuranceVault TotalStake (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: InsuranceVault AccRewardPerShare (r:1 w:0)
	/// Proof: InsuranceVault AccRewardPerShare (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: InsuranceVault StakeTimestamp (r:0 w:1)
	/// Proof: InsuranceVault StakeTimestamp (max_values: None, max_size: Some(52), added: 2527, mode: MaxEncodedLen)
	/// Storage: InsuranceVault RewardDebt (r:0 w:1)
	/// Proof: InsuranceVault RewardDebt (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	fn stake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `539`
		//  Estimated: `6208`
		// Minimum execution time: 64_000_000 picoseconds.
		Weight::from_parts(65_000_000, 6208)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(8_u64))
	}
	/// Storage: Assets Asset (r:1 w:1)
	/// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
	/// Storage: Assets Account (r:2 w:2)
	/// Proof: Assets Account (max_values: None, max_size: Some(134), added: 2609, mode: MaxEncodedLen)
	/// Storage: InsuranceVault TotalStake (r:1 w:0)
	/// Proof: InsuranceVault TotalStake (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: InsuranceVault AccRewardPerShare (r:1 w:1)
	/// Proof: InsuranceVault AccRewardPerShare (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	fn add_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `6208`
		// Minimum execution time: 58_000_000 picoseconds.
		Weight::from_parts(59_000_000, 6208)
			.saturating_add(T::DbWeight::get().reads(5_u64))
			.saturating_add(T::DbWeight::get().writes(4_u64))
	}
	/// Storage: InsuranceVault UserStake (r:1 w:0)
	/// Proof: InsuranceVault UserStake (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	/// Storage: InsuranceVault AccRewardPerShare (r:1 w:0)
	/// Proof: InsuranceVault AccRewardPerShare (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: InsuranceVault RewardDebt (r:1 w:1)
	/// Proof: InsuranceVault RewardDebt (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	/// Storage: InsuranceVault PendingReward (r:1 w:1)
	/// Proof: InsuranceVault PendingReward (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	/// Storage: Assets Asset (r:1 w:1)
	/// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
	/// Storage: Assets Account (r:2 w:2)
	/// Proof: Assets Account (max_values: None, max_size: Some(134), added: 2609, mode: MaxEncodedLen)
	fn claim() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `797`
		//  Estimated: `6208`
		// Minimum execution time: 63_000_000 picoseconds.
		Weight::from_parts(64_000_000, 6208)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
	/// Storage: InsuranceVault UserStake (r:1 w:1)
	/// Proof: InsuranceVault UserStake (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	/// Storage: InsuranceVault StakeTimestamp (r:1 w:0)
	/// Proof: InsuranceVault StakeTimestamp (max_values: None, max_size: Some(52), added: 2527, mode: MaxEncodedLen)
	/// Storage: InsuranceVault AccRewardPerShare (r:1 w:0)
	/// Proof: InsuranceVault AccRewardPerShare (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: InsuranceVault RewardDebt (r:1 w:1)
	/// Proof: InsuranceVault RewardDebt (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	/// Storage: InsuranceVault TotalStake (r:1 w:1)
	/// Proof: InsuranceVault TotalStake (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Assets Asset (r:1 w:1)
	/// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
	/// Storage: Assets Account (r:2 w:2)
	/// Proof: Assets Account (max_values: None, max_size: Some(134), added: 2609, mode: MaxEncodedLen)
	fn unstake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `828`
		//  Estimated: `6208`
		// Minimum execution time: 70_000_000 picoseconds.
		Weight::from_parts(75_000_000, 6208)
			.saturating_add(T::DbWeight::get().reads(8_u64))
			.saturating_add(T::DbWeight::get().writes(6_u64))
	}
	/// Storage: InsuranceVault UserStake (r:1 w:0)
	/// Proof: InsuranceVault UserStake (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	/// Storage: InsuranceVault StakeTimestamp (r:1 w:1)
	/// Proof: InsuranceVault StakeTimestamp (max_values: None, max_size: Some(52), added: 2527, mode: MaxEncodedLen)
	/// Storage: InsuranceVault MinStakeDuration (r:1 w:0)
	/// Proof: InsuranceVault MinStakeDuration (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: InsuranceVault AccRewardPerShare (r:1 w:0)
	/// Proof: InsuranceVault AccRewardPerShare (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: InsuranceVault RewardDebt (r:1 w:1)
	/// Proof: InsuranceVault RewardDebt (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	/// Storage: InsuranceVault PendingReward (r:1 w:1)
	/// Proof: InsuranceVault PendingReward (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	/// Storage: InsuranceVault TotalStake (r:1 w:1)
	/// Proof: InsuranceVault TotalStake (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Assets Asset (r:1 w:1)
	/// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
	/// Storage: Assets Account (r:2 w:2)
	/// Proof: Assets Account (max_values: None, max_size: Some(134), added: 2609, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn exit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `967`
		//  Estimated: `6208`
		// Minimum execution time: 101_000_000 picoseconds.
		Weight::from_parts(102_000_000, 6208)
			.saturating_add(T::DbWeight::get().reads(11_u64))
			.saturating_add(T::DbWeight::get().writes(8_u64))
	}
	/// Storage: InsuranceVault MinStakeDuration (r:0 w:1)
	/// Proof: InsuranceVault MinStakeDuration (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	fn set_min_stake_duration() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 7_000_000 picoseconds.
		Weight::from_parts(8_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1_u64))
	}
	/// Storage: InsuranceVault ClearingAccount (r:1 w:0)
	/// Proof: InsuranceVault ClearingAccount (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Assets Asset (r:1 w:1)
	/// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
	/// Storage: Assets Account (r:2 w:2)
	/// Proof: Assets Account (max_values: None, max_size: Some(134), added: 2609, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: InsuranceVault TotalStake (r:1 w:0)
	/// Proof: InsuranceVault TotalStake (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: InsuranceVault AccRewardPerShare (r:1 w:1)
	/// Proof: InsuranceVault AccRewardPerShare (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	fn compensate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `822`
		//  Estimated: `6208`
		// Minimum execution time: 63_000_000 picoseconds.
		Weight::from_parts(69_000_000, 6208)
			.saturating_add(T::DbWeight::get().reads(7_u64))
			.saturating_add(T::DbWeight::get().writes(5_u64))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	/// Storage: InsuranceVault UserStake (r:1 w:1)
	/// Proof: InsuranceVault UserStake (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	/// Storage: Assets Asset (r:1 w:1)
	/// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
	/// Storage: Assets Account (r:2 w:2)
	/// Proof: Assets Account (max_values: None, max_size: Some(134), added: 2609, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: InsuranceVault TotalStake (r:1 w:1)
	/// Proof: InsuranceVault TotalStake (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: InsuranceVault AccRewardPerShare (r:1 w:0)
	/// Proof: InsuranceVault AccRewardPerShare (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: InsuranceVault StakeTimestamp (r:0 w:1)
	/// Proof: InsuranceVault StakeTimestamp (max_values: None, max_size: Some(52), added: 2527, mode: MaxEncodedLen)
	/// Storage: InsuranceVault RewardDebt (r:0 w:1)
	/// Proof: InsuranceVault RewardDebt (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	fn stake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `539`
		//  Estimated: `6208`
		// Minimum execution time: 64_000_000 picoseconds.
		Weight::from_parts(65_000_000, 6208)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(8_u64))
	}
	/// Storage: Assets Asset (r:1 w:1)
	/// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
	/// Storage: Assets Account (r:2 w:2)
	/// Proof: Assets Account (max_values: None, max_size: Some(134), added: 2609, mode: MaxEncodedLen)
	/// Storage: InsuranceVault TotalStake (r:1 w:0)
	/// Proof: InsuranceVault TotalStake (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: InsuranceVault AccRewardPerShare (r:1 w:1)
	/// Proof: InsuranceVault AccRewardPerShare (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	fn add_reward() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `760`
		//  Estimated: `6208`
		// Minimum execution time: 58_000_000 picoseconds.
		Weight::from_parts(59_000_000, 6208)
			.saturating_add(RocksDbWeight::get().reads(5_u64))
			.saturating_add(RocksDbWeight::get().writes(4_u64))
	}
	/// Storage: InsuranceVault UserStake (r:1 w:0)
	/// Proof: InsuranceVault UserStake (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	/// Storage: InsuranceVault AccRewardPerShare (r:1 w:0)
	/// Proof: InsuranceVault AccRewardPerShare (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: InsuranceVault RewardDebt (r:1 w:1)
	/// Proof: InsuranceVault RewardDebt (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	/// Storage: InsuranceVault PendingReward (r:1 w:1)
	/// Proof: InsuranceVault PendingReward (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	/// Storage: Assets Asset (r:1 w:1)
	/// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
	/// Storage: Assets Account (r:2 w:2)
	/// Proof: Assets Account (max_values: None, max_size: Some(134), added: 2609, mode: MaxEncodedLen)
	fn claim() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `797`
		//  Estimated: `6208`
		// Minimum execution time: 63_000_000 picoseconds.
		Weight::from_parts(64_000_000, 6208)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
	/// Storage: InsuranceVault UserStake (r:1 w:1)
	/// Proof: InsuranceVault UserStake (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	/// Storage: InsuranceVault StakeTimestamp (r:1 w:0)
	/// Proof: InsuranceVault StakeTimestamp (max_values: None, max_size: Some(52), added: 2527, mode: MaxEncodedLen)
	/// Storage: InsuranceVault AccRewardPerShare (r:1 w:0)
	/// Proof: InsuranceVault AccRewardPerShare (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: InsuranceVault RewardDebt (r:1 w:1)
	/// Proof: InsuranceVault RewardDebt (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	/// Storage: InsuranceVault TotalStake (r:1 w:1)
	/// Proof: InsuranceVault TotalStake (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Assets Asset (r:1 w:1)
	/// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
	/// Storage: Assets Account (r:2 w:2)
	/// Proof: Assets Account (max_values: None, max_size: Some(134), added: 2609, mode: MaxEncodedLen)
	fn unstake() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `828`
		//  Estimated: `6208`
		// Minimum execution time: 70_000_000 picoseconds.
		Weight::from_parts(75_000_000, 6208)
			.saturating_add(RocksDbWeight::get().reads(8_u64))
			.saturating_add(RocksDbWeight::get().writes(6_u64))
	}
	/// Storage: InsuranceVault UserStake (r:1 w:0)
	/// Proof: InsuranceVault UserStake (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	/// Storage: InsuranceVault StakeTimestamp (r:1 w:1)
	/// Proof: InsuranceVault StakeTimestamp (max_values: None, max_size: Some(52), added: 2527, mode: MaxEncodedLen)
	/// Storage: InsuranceVault MinStakeDuration (r:1 w:0)
	/// Proof: InsuranceVault MinStakeDuration (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: InsuranceVault AccRewardPerShare (r:1 w:0)
	/// Proof: InsuranceVault AccRewardPerShare (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: InsuranceVault RewardDebt (r:1 w:1)
	/// Proof: InsuranceVault RewardDebt (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	/// Storage: InsuranceVault PendingReward (r:1 w:1)
	/// Proof: InsuranceVault PendingReward (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	/// Storage: InsuranceVault TotalStake (r:1 w:1)
	/// Proof: InsuranceVault TotalStake (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: Assets Asset (r:1 w:1)
	/// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
	/// Storage: Assets Account (r:2 w:2)
	/// Proof: Assets Account (max_values: None, max_size: Some(134), added: 2609, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	fn exit() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `967`
		//  Estimated: `6208`
		// Minimum execution time: 101_000_000 picoseconds.
		Weight::from_parts(102_000_000, 6208)
			.saturating_add(RocksDbWeight::get().reads(11_u64))
			.saturating_add(RocksDbWeight::get().writes(8_u64))
	}
	/// Storage: InsuranceVault MinStakeDuration (r:0 w:1)
	/// Proof: InsuranceVault MinStakeDuration (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	fn set_min_stake_duration() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `0`
		// Minimum execution time: 7_000_000 picoseconds.
		Weight::from_parts(8_000_000, 0)
			.saturating_add(RocksDbWeight::get().writes(1_u64))
	}
	/// Storage: InsuranceVault ClearingAccount (r:1 w:0)
	/// Proof: InsuranceVault ClearingAccount (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
	/// Storage: Assets Asset (r:1 w:1)
	/// Proof: Assets Asset (max_values: None, max_size: Some(210), added: 2685, mode: MaxEncodedLen)
	/// Storage: Assets Account (r:2 w:2)
	/// Proof: Assets Account (max_values: None, max_size: Some(134), added: 2609, mode: MaxEncodedLen)
	/// Storage: System Account (r:1 w:1)
	/// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
	/// Storage: InsuranceVault TotalStake (r:1 w:0)
	/// Proof: InsuranceVault TotalStake (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	/// Storage: InsuranceVault AccRewardPerShare (r:1 w:1)
	/// Proof: InsuranceVault AccRewardPerShare (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
	fn compensate() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `822`
		//  Estimated: `6208`
		// Minimum execution time: 63_000_000 picoseconds.
		Weight::from_parts(69_000_000, 6208)
			.saturating_add(RocksDbWeight::get().reads(7_u64))
			.saturating_add(RocksDbWeight::get().writes(5_u64))
	}
}
